### ISSUE TITLE
Palace hedge crashes the OpenCiv1 (solved), Palace dialog has additional line (solved), Palace sections get wrong bitmaps displayed

### ISSUE THREAD

**Issue by axx0** [rajko-horvat/OpenCiv1#17]
![Clipboard02](https://github.com/rajko-horvat/OpenCiv1/assets/21365802/b5913d5a-de18-4f9d-a86d-80a0c3fd85fc)

**Comment by rajko-horvat** [comment]
This can be also observed on some Meet with king dialogs.

**Comment by rajko-horvat** [comment]
Seems to be fixed as of last commit. Needs additional checks if all dialogs are fixed.

**Comment by axx0** [comment]
Playing with the latest commit, the hedge is now ok and also the extra line in dialogs doesn't appear no more.

But now I get this mixing of sections:
![Clipboard02](https://github.com/rajko-horvat/OpenCiv1/assets/21365802/14373c0d-6f6a-40e1-b03e-bc8dbdf27a54)

**Comment by rajko-horvat** [comment]
I guess this is another bug. Perhaps it's related with memory corruption regarding bitmap ID's.

**Comment by rajko-horvat** [comment]
After a further investigation, it appears like a normal behavior.

![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/4008bd1f-2b75-4d74-85d1-b7e1cc0c8264)

And after an upgrade:
![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/4783841e-d054-44ad-b83e-713102d20647)

This doesn't look like a bug, but as a normal behavior.

**Comment by axx0** [comment]
Well, good then. 
Surprisingly, even after playing this game for 30 years I'm still not entirely familiar with it.
