### ISSUE TITLE
City view has bug with disorder animation

### ISSUE THREAD

**Issue by axx0** [rajko-horvat/OpenCiv1#18]
The walking of protestors is a bit wonky.
![Clipboard04](https://github.com/rajko-horvat/OpenCiv1/assets/21365802/6d1cc73d-5299-4580-be09-c1a1b7f48c96)

**Comment by rajko-horvat** [comment]
I don't know how to intentionally provoke disorder. Could you please share save game where you have disorder so I can check what's wrong with the animation.

**Comment by axx0** [comment]
Disorder will start at end of turn.
[CIV1.zip](https://github.com/rajko-horvat/OpenCiv1/files/13845382/CIV1.zip)

**Comment by rajko-horvat** [comment]
Thanks that save file helped a lot.

I fixed it as of last commit:
![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/016eabbf-d3d3-4294-bd16-dbf23546b59f)

**Comment by axx0** [comment]
Can confirm it works ok.
