### ISSUE TITLE
Advisor dialog has misaligned Advisor image

### ISSUE THREAD

**Issue by axx0** [rajko-horvat/OpenCiv1#19]
![image](https://github.com/rajko-horvat/OpenCiv1/assets/21365802/2946aac3-082d-4ac0-a00a-2e56e91719bc)

**Comment by rajko-horvat** [comment]
Appears to be fixed as of last commit.

![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/37505696-6ff4-4065-9721-63bca4bdcff4)

**Comment by rajko-horvat** [comment]
Appears to be completely fixed.
