### ISSUE TITLE
Log file too big

### ISSUE THREAD

**Issue by axx0** [rajko-horvat/OpenCiv1#21]
Log file made by [this](https://github.com/rajko-horvat/OpenCiv1/issues/20#issue-2052971985) error is 3 GB large. Consequently I can't open it in notepad++ let alone notepad.

Edit: After I deleted the log file and repeated the error, the size of the log.txt is only 80 MB (it's still too large to be uploaded on github). Does the log fill after each game session?

**Comment by rajko-horvat** [comment]
Tried to reduce log file with latest commit. The Glogg (the fast, smart log explorer) can be used to view large log files.
