### ISSUE TITLE
Question mark added after the first letter of some menu items

### ISSUE THREAD

**Issue by richardpenman** [rajko-horvat/OpenCiv1#22]
I noticed a question mark is added after the first letter of some menu items:

![Screenshot_2023-12-30_18-27-14](https://github.com/rajko-horvat/OpenCiv1/assets/26063146/801f281b-0c53-46d3-be59-b4bcaa6f2ecf)

Note this was tested with MonoDevelop + Linux + Civ v 475.01. (Will test again with 475.05 if can find it.)

**Comment by richardpenman** [comment]
Also experienced by Lord_Hill:
https://forums.civfanatics.com/threads/rewrite-of-civilization-1-source-code-open-civilization-1-project.682623/page-5#post-16512034

**Comment by rajko-horvat** [comment]
Fixed as of last commit
