### ISSUE TITLE
Palace transitions

### ISSUE THREAD

**Issue by richardpenman** [rajko-horvat/OpenCiv1#24]
The palace sections appear immediately rather than the transition animation. 

Also noticed by axx: https://forums.civfanatics.com/threads/rewrite-of-civilization-1-source-code-open-civilization-1-project.682623/page-7#post-16546187

**Comment by rajko-horvat** [comment]
I'm not sure if this is really an issue since this will not be an exact copy of the game...
The animations will change anyway with the eventual introduction of new graphics and the web port.

**Comment by richardpenman** [comment]
Got it, makes sense.
