### ISSUE TITLE
Blank line added between starting technologies

### ISSUE THREAD

**Issue by richardpenman** [rajko-horvat/OpenCiv1#26]
I noticed a minor formatting issue - a blank line is added between the starting technologies:

![screenshot-start-technologies](https://github.com/rajko-horvat/OpenCiv1/assets/26063146/a5b595a0-dc80-4942-a635-de5f59ca8d80)

**Comment by rajko-horvat** [comment]
Well, these little graphics glitches still exist. I'm not trying to exactly duplicate everything to a pixel ;)

**Comment by richardpenman** [comment]
What kind of bug reports or assistance would be useful for now? I want to see this project succeed and assist it in the most effective way. I have experience with backend programming (mostly Python, Java, C++) but not assembly.

**Comment by rajko-horvat** [comment]
Mostly some gameplay or serious bugs that need attention right now.
I have noticed this line space and I think it's related to additional line that is added in some menus and dialogs, and this will be fixed soon.
Right now I'm introducing parameters to all of the functions and trying to reduce virtual assembly code clutter. After that I will introduce more global variables and strings until code no more relies on exe's binary resources (BinaryResources.bin).

**Comment by rajko-horvat** [comment]
> ...I want to see this project succeed and assist it in the most effective way...

As do I ;)

**Comment by rajko-horvat** [comment]
Seems to be fixed as of last commit. Needs additional checks if all dialogs are fixed.

**Comment by richardpenman** [comment]
Yep works for me also in latest commit
