### ISSUE TITLE
Moving the unit beyond the map display doesn't update the view of map properly

### ISSUE THREAD

**Issue by axx0** [rajko-horvat/OpenCiv1#28]
The trireme moves to the edge of map but the map view doesn't change. It also doesn't change when trireme moves beyond the view.

![Clipboard04](https://github.com/rajko-horvat/OpenCiv1/assets/21365802/854bc322-4fe1-45b6-8df4-3e63136f5eb9)

**Comment by rajko-horvat** [comment]
I noticed a couple of map issues in the original CIV.EXE so I guess the issue will be resolved when we tackle the map display altogether.

**Comment by rajko-horvat** [comment]
Should work correctly as of last commit.

**Comment by axx0** [comment]
It works.
