### ISSUE TITLE
Captured city disappears

### ISSUE THREAD

**Issue by richardpenman** [rajko-horvat/OpenCiv1#32]
I found when I capture this city of size 2 the game enters the city screen but then afterwards the city is gone:

![Screenshot_attack](https://github.com/rajko-horvat/OpenCiv1/assets/26063146/63408e82-9df8-4747-b55d-d670bd4f9073)
![Screenshot_2024-01-05_19-43-38](https://github.com/rajko-horvat/OpenCiv1/assets/26063146/c2a8915e-3abd-4122-9be1-5397ab5d68fb)
![Screenshot_2024-01-05_19-46-06](https://github.com/rajko-horvat/OpenCiv1/assets/26063146/3d010f3c-8482-485e-8593-4bfe42992b47)

 

[AttackSave.zip](https://github.com/rajko-horvat/OpenCiv1/files/13848241/AttackSave.zip)

**Comment by rajko-horvat** [comment]
Curious, I tried with CIV.EXE but it transferred the city properly. This will have to wait until I return from my trip next week.

**Comment by richardpenman** [comment]
Interestingly that captured city just fell into civil disorder, so it still exists but I can't see it!

**Comment by rajko-horvat** [comment]
Yes, the GameState show city exists, but for some reason it's not shown on the map... Will check it soon

**Comment by rajko-horvat** [comment]
Should work correctly as of last commit.

**Comment by richardpenman** [comment]
Thanks! Confirms that new captured cities are visible. 
Already captured cities are still invisible, but I don't think need to bother about that.

**Comment by rajko-horvat** [comment]
Yes, already captured cities that are invisible are marked as deleted in game resources. Game save can be hacked to show the cities that are invisible, but I guess it's not needed as the bug that deleted captured cities is resolved.
