### ISSUE TITLE
Right click city improvement shows incorrect description

### ISSUE THREAD

**Issue by richardpenman** [rajko-horvat/OpenCiv1#33]
In city view when right click an improvement the wrong civilopedia description is shown.

For Palace get "None" (screenshot below) and for barracks get "Palace", so I expect is an off by one error. All the units I checked were correct.

![Screenshot_2024-01-07_11-49-54](https://github.com/rajko-horvat/OpenCiv1/assets/26063146/5606997c-8470-4697-8bb3-6f2ab3977f30)

**Comment by rajko-horvat** [comment]
Thanks, will check it out.

**Comment by rajko-horvat** [comment]
Hi, I mistakenly transferred NEG (-1) as NOT (~).
Should work correctly as of last commit.

**Comment by richardpenman** [comment]
Thanks, confirmed this is fixed
