### ISSUE TITLE
Resources missing in city resources map

### ISSUE THREAD

**Issue by axx0** [rajko-horvat/OpenCiv1#34]
As shown in picture, only 2 out of 4 resources on the map are visible. Also, moving the resource east of city to north makes it invisible.
![Clipboard02](https://github.com/rajko-horvat/OpenCiv1/assets/21365802/04a017e9-8b92-4c20-b784-98c50470e0b7)

**Comment by rajko-horvat** [comment]
Huh, you guys are really testing the game, and that's great ;)

**Comment by rajko-horvat** [comment]
Should be fixed as of last commit.

**Comment by axx0** [comment]
Seems to work now.
