### ISSUE TITLE
Move to .NET Core 8 ?

### ISSUE THREAD

**Issue by maximilien-noal** [rajko-horvat/OpenCiv1#35]
Hi !

Using the latest .NET would make this cross platform and enable more contributions from people who do not use Windows.

I'm curious, what would be the main issues preventing that, and would you accept such a PR ?

**Comment by rajko-horvat** [comment]
**I was also thinking about transition to .NET Core.**

But few issues are preventing me to do just that:

1. You can't hook Key Up/Down and Mouse Up/Down/Move events, also, there are no alternatives. This specifically impacts Alt+?, Ctrl+? key combinations and map display (moving, etc.).
2.  Paint event, couldn't find real alternative.
3. The code is still rough as there are a couple of objects still to be translated to managed state, also, the original dialogs would need to be translated to real .NET Forms/Dialogs.

I'm doing this step by step, and sure enough there will come a time when the gap will be almost non existent, but for now these are real problems preventing me to migrate to .NET Core.

**Comment by maximilien-noal** [comment]
For the UI side of things, I'm sure everything can be replaced with AvaloniaUI. Unless you use MDI (Multi Document Interface), which is not present.

1. Spice86 (a similar project that I contribute to. We focus on Dune) hooks up those events with AvaloniaUI with no problems:
2. See this issue for the paint event: https://github.com/AvaloniaUI/Avalonia/discussions/12306
3. I think this can be preserved and that the move to .NET 8 + AvaloniaUI won't change that... ? Is there more to it ?

There is a mid-step than I see: Still using WinForms, but the latest .NET 8 introduces binding APIs. This would make the 

WinForms code, and furthermore code-behind code (The code ) tend to mix business logic with UI logic and form spagetthi code. 

The UI side of things seems simple enough to be fixed very quickly, before it becomes a problem. WinForms is very problematic with this, very quickly (10 years of experience dealing with it).

WinForms in .NET 8 introduces binding APIs that enables the usage of the MVVM pattern, which makes things easier to maintain in the long run, and separate UI logic from business logic.

(I've done a ton of WinForms / WPF / AvaloniaUI, and a ton of .NET work, as you can see)

**Comment by rajko-horvat** [comment]
**These are good news indeed :)**

For now OpenCiv1 depends on one simple WinForm (MainForm.cs) which hooks:

- KeyPress,
- KeyDown,
- MouseMove,
- MouseDown,
- MouseUp,
- Paint,
- FormClosing (For 'Are you sure you want to quit?' message)

There are a few buttons, Pause/Run button, and Hide/Display screen 1-n

You can see details in MainForm.cs

If you can perhaps contribute in alternative MainForm.cs code that would be great, as all other things in code should work also in .Net Core.
I'm sorry, but for now I really don't have time (already late with a few projects) to invest in learning new .NET Core things. For now, I have done one medium complexity .NET Core WebApp (Revigo) which works great, it's a little different than ASP.NET, but overall the experience has been very positive.

Perhaps there are a few NULL object references, but these can be resolved with time (as .NET Core is compatible with NULL object references).

I'm sure there are many people who will be happier with .NET Core version.

**However, I plan to port code later on to JavaScript, as that would give us true Multiplatform capabilities, Multiplayer, real Hall of fame, game Save sharing, etc.**

**Of course everyone will be able to run their own private server ;)** for offline playing, etc.

**Comment by maximilien-noal** [comment]
Thank you for this detailed answer.

Actually, the very first contribution would be to move to SDK-style .csproj files. This does not imply by itself a move from .NET Framework.

> However, I plan to port code later on to JavaScript, as that would give us true Multiplatform capabilities, Multiplayer, real Hall of fame, game Save sharing, etc.

I'd use Blazor for that, but it's just because I really dislike Javascript, and keeping the same C# codebase would save time and efforts. Blazor uses C# seamlessly on the server side and on the client side. AvaloniaUI can do it too, with WASM, but Blazor is more documented. Blazor still can use JS modules if needed.

**Comment by rajko-horvat** [comment]
I completely overlooked Blazer ;)
Thanks for pointing me the right way will look at it later.

I specifically meant to upgrade to .NET Core/MAUI. Don't know if that supports all events that I need for conversion.

**Comment by LowLevelMahn** [comment]
...and join the discord channel - there are so few reversing people out there :(

**Comment by rajko-horvat** [comment]
Did a conversion of project to a newer format (SDK-style .csproj files).

**Comment by rajko-horvat** [comment]
> ...and join the discord channel - there are so few reversing people out there :(

The invite link expired...

**Comment by maximilien-noal** [comment]
Here is a new one https://discord.com/invite/bXtzpqPj

I will send a PR today for net core.

**Comment by rajko-horvat** [comment]
I tried today on MacOS:

![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/f0151051-deab-42b0-babe-7227ce0a1197)

It works!!!

**Comment by rajko-horvat** [comment]
I would suggest that everyone who wants to participate in testing OpenCiv1 before release do so ;)

**Comment by axx0** [comment]
Very good! I actually suggest you show these two screenshots in the readme section.

**Comment by richardpenman** [comment]
Is there a way to increase the window size?

**Comment by maximilien-noal** [comment]
By default, there should be.

**Comment by rajko-horvat** [comment]
> By default, there should be.

I fixed the size of the main window.

**Comment by maximilien-noal** [comment]
> No, not yet :( The game is built for 320x200 and I increased it to 640x400 by doubling pixel size. Later on, when I translate more code then it will be possible. Well I could scale the image further, but the game resolution will stay the same.

You can put a viewbox as a parent to the Image control. It will scale it properly at any size.

**Comment by rajko-horvat** [comment]
> > No, not yet :( The game is built for 320x200 and I increased it to 640x400 by doubling pixel size. Later on, when I translate more code then it will be possible. Well I could scale the image further, but the game resolution will stay the same.
> 
> You can put a viewbox as a parent to the Image control. It will scale it properly at any size.

Yes, perhaps that is what I should do ;)

**Comment by rajko-horvat** [comment]
Wow, so easy, and it works instantly ;)
I committed the changes.

**Comment by richardpenman** [comment]
Amazing, now full screen mode works! This will make play testing the game easier.

<img width="778" alt="Screenshot 2024-03-08 at 6 26 16 AM" src="https://github.com/rajko-horvat/OpenCiv1/assets/26063146/c3a3ec6c-5038-4ede-9a7a-8d789a0e1755">

**Comment by rajko-horvat** [comment]
I'm going to close this, a project was successfully migrated to .NET 8 and Avalonia UI

**Comment by kovacm** [comment]
> > Quick question: I just install ".NET SDK Arm64 (Apple Silicon)" and do (as [@richardpenman](https://github.com/richardpenman) suggested): $ cd OpenCiv1/src $ dotnet run
> > but all I get is new process OpenCiv1 but without any window. Do I need to install some additional stuff? (I really do not have experience with M$ stuff...)
> 
> I never tried to compile and run on ARM64 platform (yet) Hm, the Master release is a little bit old. You could try to update Avalonia components (perhaps that could be the problem).

My mistake! I did not put original files in: ~/Dos/Civ1 !
So build from master works without any additional packages, just "dotnet run" (with original files in ~/Dos/Civ1)
