### ISSUE TITLE
Errors with Earth map 

### ISSUE THREAD

**Issue by richardpenman** [rajko-horvat/OpenCiv1#42]
I am testing the latest version on OSX and custom maps work fine.

However with Earth the map is a giant block of grassland:

<img width="1013" alt="Screenshot 2024-03-08 at 8 53 17 PM" src="https://github.com/rajko-horvat/OpenCiv1/assets/26063146/d8532a0f-b277-47dc-9ceb-7f76addd8f6b">

And this is not regular grassland:

<img width="1000" alt="Screenshot 2024-03-08 at 8 53 43 PM" src="https://github.com/rajko-horvat/OpenCiv1/assets/26063146/841cea68-9bb8-4cfe-8d75-8a34f15488b7">

The grassland is so fertile it produces a population + improvement + pollution every turn - could make for an interesting game! Save game is attached if anyone is interested.

This was with Zulu. I tried again as Aztec/Mongol and the start position is at sea:

<img width="259" alt="Screenshot 2024-03-08 at 8 59 31 PM" src="https://github.com/rajko-horvat/OpenCiv1/assets/26063146/8c3ce187-4e5f-4a12-b733-e63bb6ad5ae8">

[CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14538620/CIVIL0.zip)

**Comment by rajko-horvat** [comment]
Interesting ;)

**Comment by rajko-horvat** [comment]
Earth image is not loaded correctly, will investigate...
![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/459c4b66-36ac-42f4-993c-cfa595208e74)

**Comment by rajko-horvat** [comment]
I think I fixed it.
![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/caaf0604-8130-4a52-920d-571bc3a0cad7)

Will commit in a sec.

**Comment by richardpenman** [comment]
Confirmed fixed! 

Though I don't understand how [commit/9e5bd85496213f47fc7acaae859c04770b7e5452](https://github.com/rajko-horvat/OpenCiv1/commit/9e5bd85496213f47fc7acaae859c04770b7e5452) fixed this. This seems to be rendering changes - what caused the grassland to be so productive?

**Comment by rajko-horvat** [comment]
> Confirmed fixed!
> 
> Though I don't understand how [commit/9e5bd85496213f47fc7acaae859c04770b7e5452](https://github.com/rajko-horvat/OpenCiv1/commit/9e5bd85496213f47fc7acaae859c04770b7e5452) fixed this. This seems to be rendering changes - what caused the grassland to be so productive?

Probably some flags got messed up on the map, so preprogrammed things got messed up.
