### ISSUE TITLE
About my own copies of the DOS Civilization game

### ISSUE THREAD

**Issue by r1j1k** [rajko-horvat/OpenCiv1#43]
**Describe the bug**
Tried both of my backups versions
Both have SP256.PAL not SP257.PAL
Got error all the time:
Missing resource file ~\OpenCiv1-Alpha7-win-x64\SP257.PAL. Please ensure that the file exists at
specified path.

**To Reproduce**
1. Go to '~\OpenCiv1-Alpha7-win-x64\'
2. Click on 'OpenCiv1.exe'
3. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/rajko-horvat/OpenCiv1/assets/8223035/e6abda70-dd1a-49bb-b467-ccfffa3b62af)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [Build 22631]

**Additional context**
Version available by URL https://archive.org/details/CIVILIZATION_201902 worked fine however

So NOT every owned copy works

**Comment by rajko-horvat** [comment]
These are requirements for version 475.05. However, SP256.PAL and SP257.PAL are identical and SP256.PAL can be safely copied to SP257.PAL.
Some users have deleted the SP257.PAL as it appears not to be used by the original CIV at all. Just to be safe I have left this as resource requirement.
I will later consolidate file requirements as there are still some strings that are read from CIV.EXE resources.

**Comment by rajko-horvat** [comment]
Also tried the copy you provided with exact path and setup and I could not reproduce the error that you encountered.

**Comment by r1j1k** [comment]
> Also tried the copy you provided with exact path and setup on Windows 10 (19045.4170) and I could not reproduce the error that you encountered.

The one that Web Archive provided?
Yes as I said this one works fine

**Comment by rajko-horvat** [comment]
> The one that Web Archive provided? Yes as I said this one works fine

Yes, SP256 and SP257 are version dependent, and I just wanted to test anyway... ;)
