### ISSUE TITLE
Crashes due to out-of-bounds errors

### ISSUE THREAD

**Issue by hadabascus** [rajko-horvat/OpenCiv1#44]
Various crashes with error "Exception message: Index was outside the bounds of the array". To solve these, the decompiled code needs to be translated to managed code, see [comment below](https://github.com/rajko-horvat/OpenCiv1/issues/44#issuecomment-2027686079).

**Comment by rajko-horvat** [comment]
I will need a little more context, are you able to share your save game?

**Comment by hadabascus** [comment]
[CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14804208/CIVIL0.zip)

**Comment by rajko-horvat** [comment]
Yes, this one, Index out of range is confirmed. I have made a fix for it and the fix will became a part of the master as soon as I finish UnitDefinition structure translation.

**Comment by hadabascus** [comment]
I cannot reproduce the crash in the above save file in anymore.

In this save file, after ending the turn, the game crashes before the next turn begins:
[CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14806643/CIVIL0.zip)
This occurs both in [master](https://github.com/rajko-horvat/OpenCiv1) and in [Translate-UnitDefinition](https://github.com/rajko-horvat/OpenCiv1/tree/Translate-UnitDefinition).

**Comment by rajko-horvat** [comment]
The fix is under Translate-UnitDefinition (this is the current branch until UnitDefinition structure is fully translated to managed code)

**Comment by rajko-horvat** [comment]
Also, there are a lot of unchecked playerID -1 references which translates to 0xffff and ends God knows where... I'm just saying there will be more Array index out of range errors until we translate all of the code to managed and check all of the rules ;)

**Comment by hadabascus** [comment]
Yeah, crashes a bit too often due to out-of-bounds to finish a game.

Crash when attacking the enemy ship:
[CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14808639/CIVIL0.zip)

**Comment by rajko-horvat** [comment]
> Yeah, crashes a bit too often due to out-of-bounds to finish a game.
> 
> Crash when attacking the enemy ship: [CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14808639/CIVIL0.zip)

Sorry to hear that :(
You never know what skeletons lay in the code until you start to take it apart, and apparently Sid (as a principal programmer on this one) has left us with many skeletons...

Will commit a fix in a few minutes.

**Comment by rajko-horvat** [comment]
> Various crashes with error "Exception message: Index was outside the bounds of the array". To solve these, the decompiled code needs to be translated to managed code, see [comment below](https://github.com/rajko-horvat/OpenCiv1/issues/44#issuecomment-2027686079).

Well, I think that it's good to see where all those Array Index Is Out Of Bounds come from. I'm just saying it's good to test the game even in this alpha stage ;)

**Comment by hadabascus** [comment]
Thanks for the fix for the "attacking the enemy ship" crash!

**Comment by hadabascus** [comment]
Are these crash reports still useful at this stage, or should I wait until you have finished fully translating the UnitDefinition structure to managed code?

**Comment by rajko-horvat** [comment]
Yes, they are useful.
Please keep them coming ;)

**Comment by hadabascus** [comment]
Have not had any further crashes from out-of-bounds errors. Game seems stable now.

The current version is a _huge_ improvement over version Alpha 7. Plays almost as well as the original version, sometimes probably even better, with less integer overflows doing strange stuff. I think Alpha stage is over ;)

**Comment by rajko-horvat** [comment]
> Have not had any further crashes from out-of-bounds errors. Game seems stable now.
> 
Glad to hear that :))

> The current version is a _huge_ improvement over version Alpha 7. Plays almost as well as the original version, sometimes probably even better, with less integer overflows doing strange stuff. I think Alpha stage is over ;)

Perhaps, based on your other bug reports, not quite yet ;)

**Comment by hadabascus** [comment]
Crash when reaching the Artic.
[CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14906598/CIVIL0.zip)
![Crash1](https://github.com/rajko-horvat/OpenCiv1/assets/162590950/ee24effd-d3ca-42db-ba26-cad711074587)
![Crash2](https://github.com/rajko-horvat/OpenCiv1/assets/162590950/a61f16b1-fbd0-4425-955f-d1873320f72a)

**Comment by hadabascus** [comment]
Crash after finishing the game (in the save this happens after capturing the last city and selecting "No replay").
[CIVIL0.zip](https://github.com/user-attachments/files/15592511/CIVIL0.zip)

**Comment by rajko-horvat** [comment]
You are relentless tester and I thank you very much for your time ;)
I'm currently translating the largest code Segment_1d12 to managed code completely.

The fix for a crash was a simple one, as I didn't account for a font drawing overflow. I fixed the problem in current unstable "Transfer-unmanaged-data-to-managed-and-code-cleanup" branch. As soon as I finish translating the code completely I will merge changes with Master.

Until then you can use unstable branch for testing purposes.

**Comment by hadabascus** [comment]
Of course, no problem :) Thank you for working on this and for giving insight into what kind of bugs and issues there are with the old code.

**Comment by hadabascus** [comment]
Starting a revolution and clicking on the city "Lyons" crashes the game. Strangely, it even fails to create the `Log.txt` file.
[CIVIL0.zip](https://github.com/user-attachments/files/15748234/CIVIL0.zip)

**Comment by rajko-horvat** [comment]
In the new version the log generation is disabled by default, you have to enable it in CivGame.cs by setting enableLog=true

**Comment by rajko-horvat** [comment]
Funny thing, CheckValueRange got minimum value that is greater than maximum value, i have modified it to not produce an exception, just log entry. I will have to revisit this later and analyze why this happens... :)

The other funny thing is it looks like Sid tried to understand why stack gets corrupted sometimes and moved some vars to global namespace instead of a stack. I now know that several functions misbehaved and produced erroneous pointers (some programmers called it Pointer Hell), especially GoTo function. Today, when programming in a managed environment such a thing is virtually impossible :)

**Comment by rajko-horvat** [comment]
> Starting a revolution and clicking on the city "Lyons" crashes the game. Strangely, it even fails to create the `Log.txt` file.

How did you came up with making a Revolution, without the proper tech, would never came up with that ;)

**Comment by hadabascus** [comment]
Haha, I actually just happened to build Pyramids the previous turn :)

**Comment by rajko-horvat** [comment]
I'm going to close this as these bugs are fixed. If another array Index Out of Range error happens then a new issue should be opened for that particular array Index Out of Range error. Feel free to reopen this if needed.
