### ISSUE TITLE
Boarding a ship makes the first built unit go on sentry

### ISSUE THREAD

**Issue by hadabascus** [rajko-horvat/OpenCiv1#45]
**Describe the bug**
When boarding any ship with any unit, the first unit that your civilization has built (if still alive) goes on sentry (gets a gray silhouettes).

**To Reproduce**
1. Start the game
2. Build a Militia
3. Discover MapMaking
4. Build a Trieme
5. Board the Trieme with another Militia
6. The first-built Militia goes on sentry

**Desktop (please complete the following information):**
 - OS: Debian 12, Linux 6.1.76-1
 - Version: OpenCiv1-Alpha7-linux-x64

**Comment by rajko-horvat** [comment]
I could not replicate this bug, when I move militia on a Trireme the correct unit (unit on a Trireme goes on sentry, as expected), and the city units remain on Fortify or active.

**Comment by hadabascus** [comment]
Save file:
[CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14804284/CIVIL0.zip)

Before boarding:
![before_boarding](https://github.com/rajko-horvat/OpenCiv1/assets/162590950/09d94f6b-666a-4a8c-a8d6-4bcd6cd735e6)

Right after boarding:
![right_after_boarding](https://github.com/rajko-horvat/OpenCiv1/assets/162590950/301eeba5-bf16-4d5a-a02e-7721aeb4f13b)

**Comment by rajko-horvat** [comment]
As of last submit, I couldn't verify your bug. It appears to have been fixed after the latest release. Try to build from source, if you are not able, please let me know so I can make a weekly build.

![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/625d7836-b0e2-4585-9083-1334cb04760d)

![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/af92af64-d7f9-41cc-b5db-10922718c159)

**Comment by hadabascus** [comment]
Built from source and verified that this bug is indeed fixed.
