### ISSUE TITLE
Crash when looking at Wonders of the World (F7)

### ISSUE THREAD

**Issue by hadabascus** [rajko-horvat/OpenCiv1#47]
Occurs in both [master](https://github.com/rajko-horvat/OpenCiv1/tree/master) and in [Translate-UnitDefinition](https://github.com/rajko-horvat/OpenCiv1/tree/Translate-UnitDefinition).
Attached save: [CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14806497/CIVIL0.zip)

**Comment by rajko-horvat** [comment]
The fix is under Translate-UnitDefinition (this is the current branch until UnitDefinition structure is fully translated to managed code)
