### ISSUE TITLE
Enemy cities randomly disappearing

### ISSUE THREAD

**Issue by hadabascus** [rajko-horvat/OpenCiv1#48]
**Describe the bug**
After ending the turn, enemy cities sometimes disappear

**To Reproduce**
1. Load the following save:
[CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14899859/CIVIL0.zip)
2. End the turn.
3. Notice that Berlin disappears.

**Comment by rajko-horvat** [comment]
Couldn't reproduce that Berlin disappears with the latest version
