### ISSUE TITLE
Missing image for fortified unit

### ISSUE THREAD

**Issue by hadabascus** [rajko-horvat/OpenCiv1#50]
**Describe the bug**
Some fortified units do not have their icon.

**To Reproduce**
1. Load
[CIVIL0.zip](https://github.com/rajko-horvat/OpenCiv1/files/14899896/CIVIL0.zip)

**Screenshots**
![Fortified missing](https://github.com/rajko-horvat/OpenCiv1/assets/162590950/afd28b1e-faf9-42ec-9da4-eb582cc1cf51)

**Comment by rajko-horvat** [comment]
Fixed, it was my mistake ;)
![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/d1aadb18-07a8-42e9-a05c-21ece60c8832)
