### ISSUE TITLE
Unworked city tile

### ISSUE THREAD

**Issue by hadabascus** [rajko-horvat/OpenCiv1#51]
Clicking on an unworked tile in the city screen makes the city tile unworked.
[CIVIL0.zip](https://github.com/user-attachments/files/15739281/CIVIL0.zip)
![scrn1](https://github.com/rajko-horvat/OpenCiv1/assets/162590950/4fae479a-bf27-49b7-b04e-ae93fe2709f2)
![scrn2](https://github.com/rajko-horvat/OpenCiv1/assets/162590950/9ee60899-d47f-44ce-9f18-ca8c8ce7303e)

**Comment by rajko-horvat** [comment]
I could not reproduce the same bug with provided save game data in the current 'Transfer-unmanaged-data-to-managed-and-code-cleanup' branch.

**Comment by hadabascus** [comment]
Oops, I forgot to try on that branch.

Trying to build from the latest commit (4694467fc4bd0faa0ed9aa8a6231d1fc97bafa32) using

```
dotnet build -c Release
```

seems to fail with

```
.../OpenCiv1/src/UI/MainWindow.axaml.cs(571,14): error CS1061: 'MainWindow' does not contain a definition for 'oGame' and no accessible extension method 'oGame' accepting a first argument of type 'MainWindow' could be found (are you missing a using directive or an assembly reference?) [.../OpenCiv1/src/OpenCiv1.csproj]
```

**Comment by rajko-horvat** [comment]
Sorry, forgot to check 'Release' configuration, fixed...

**Comment by hadabascus** [comment]
Great. All works now.

**Comment by hadabascus** [comment]
Settlers cannot be built anymore, it seems,
![scrn](https://github.com/rajko-horvat/OpenCiv1/assets/162590950/40134677-6a45-47e1-b90a-3ab17ede2d38)

**Comment by rajko-horvat** [comment]
Just discovered that I have a bug in Technology tree, will fix it soon :)

**Comment by rajko-horvat** [comment]
Fixed... :)
