### ISSUE TITLE
City map does not show one worker

### ISSUE THREAD

**Issue by 1oom-fork** [rajko-horvat/OpenCiv1#56]
**Describe the bug**
Immediately after a city is founded, income from workers is shown as if both workers were involved, but only the worker in the city center is shown on the map

**Expected behavior**
Both workers should be displayed

![Screenshot_20240624_134319](https://github.com/rajko-horvat/OpenCiv1/assets/23404794/33068f50-3f0e-4122-97c9-79743f88356f)

**Comment by rajko-horvat** [comment]
Sorry, could not reproduce:
![Untitled](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/7fb04e60-098d-485f-8a6f-22513a1eaf21)

**Comment by 1oom-fork** [comment]
I have default build. I'll try to rebuild
