### ISSUE TITLE
There is no animation for building cosmetic elements of the palace

### ISSUE THREAD

**Issue by 1oom-fork** [rajko-horvat/OpenCiv1#58]
**Expected behavior**
It is expected that all animations in the game will be displayed correctly

**Comment by rajko-horvat** [comment]
No, this is a rewrite, and as such certain things will change. Just look at project milestones (Readme).

**Comment by 1oom-fork** [comment]
I don’t quite understand what you want from me in this case. I pointed out that it obviously doesn't work for me. Your task is to respond to this information in the way that is convenient for you.

**Comment by rajko-horvat** [comment]
> I don’t quite understand what you want from me in this case. I pointed out that it obviously doesn't work for me. Your task is to respond to this information in the way that is convenient for you.

Be warned!
I find such language is inappropriate, insulting and is not constructive in any way. If you insist and continue with such I will be forced to take actions. For any further information on what is acceptable conduct please take a look at our [Code of Conduct](https://github.com/rajko-horvat/OpenCiv1?tab=coc-ov-file)

And now an clarified reply to your question:

As I stated before, this rewrite doesn't aim to reconstruct all aspects of the game down to a single detail, as that would defeat the purpose of a rewrite.
Further on, the game graphics design will change in the future anyway (according to our Road map) so I find such a graphics details are not needed for a full Game experience and/or functionality.
