### ISSUE TITLE
Trouble running the release version

### ISSUE THREAD

**Issue by axx0** [rajko-horvat/OpenCiv1#8]
1. I suggest adding a note in Readme that the contents of the original game should be placed in C:\DOS\CIV, otherwise it won't work
2. After doing that and placing exe and fonts file in the folder, I get this error:

![image](https://github.com/rajko-horvat/OpenCiv1/assets/21365802/221cc8ef-01a7-4967-ae51-cee14db18ca5)

**Comment by rajko-horvat** [comment]
Well is seems like your version of civ.exe doesn't match ;) It should be 475.05

**Comment by axx0** [comment]
OK I was running this on my laptop with older civ version.
So I downloaded 475.05.

When I run the unpacker I get this:
**F:\DOS\CIV1>civunpack
Last empty byte in the last block: 0x00007b07
Joining the blocks
Block validation passed**

But then when I run openciv1 I get this:
![Clipboard01](https://github.com/rajko-horvat/OpenCiv1/assets/21365802/9c3eaa3b-5355-442d-b2f8-53ce1c19b80f)

**Comment by rajko-horvat** [comment]
You are right.
There is another hardcoded path. Will fix it tomorrow. Thanks.

**Comment by axx0** [comment]
It works!
