### ISSUE TITLE
Cannot run latest build

### ISSUE THREAD

**Issue by axx0** [rajko-horvat/OpenCiv1#9]
I'm getting **System.Exception: 'Unknown 0x21 interrupt 0x0e'**.

![image](https://github.com/rajko-horvat/OpenCiv1/assets/21365802/200297f8-e045-4e50-90e5-e4ec1cc952bf)

**Comment by rajko-horvat** [comment]
The error suggests a missing path.
I didn't have time to fix this with a meaningful message. I would suggest to check if path "C:\Dos\Civ\" exists (with all needed files), and check if build is set to Debug and not Release, as Release expects all needed files to be present at EXE path.

**Comment by axx0** [comment]
OK yeah I had to rename CIV1 to CIV. It works now.
